version: "3"

services:
  api:
    build: ./api
    ports:
      - 3001:3001
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=miniorama
      - DB_HOST=db
      - JWT_SECRET=123123
    volumes:
      - ./api:/app-api
    container_name: miniorama_api
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
